# Q1.

In order to increase the comparison of a graph we can use hue methode to put other columns measure in one figure.

# Q3.

Histogram is a type of a plot which hold the total number of counts or the percentile value in y-axis w.r.t. corresponding x-variables. When we say the number of counts it means that for a particular range in x-axis what will be the number of counts of the data points. When we talk about percentile it shows the probability occurrence of the x-variable or what percentage of data are below that particular percetile value w.r.t. particular x-variable range.

Numpy has a built-in numpy. histogram() function

# Q4.

We can use plt.figure(figsize=(10,8)) function inside the matplot.pyplot library which we scale down or up the graph.

# Q5.

In [1]:
import numpy as np

arr1 = np.array([[5,8,14],[23,35,50],[68,86,14]])
arr2 = np.array([[10,20,30],[40,50,60],[60,70,80]])

arr1 ,arr2

(array([[ 5,  8, 14],
        [23, 35, 50],
        [68, 86, 14]]),
 array([[10, 20, 30],
        [40, 50, 60],
        [60, 70, 80]]))

In [2]:
np.dot(arr1, arr2)

array([[1210, 1480, 1750],
       [4630, 5710, 6790],
       [4960, 6640, 8320]])

In [3]:
np.outer(arr1, arr2)

array([[  50,  100,  150,  200,  250,  300,  300,  350,  400],
       [  80,  160,  240,  320,  400,  480,  480,  560,  640],
       [ 140,  280,  420,  560,  700,  840,  840,  980, 1120],
       [ 230,  460,  690,  920, 1150, 1380, 1380, 1610, 1840],
       [ 350,  700, 1050, 1400, 1750, 2100, 2100, 2450, 2800],
       [ 500, 1000, 1500, 2000, 2500, 3000, 3000, 3500, 4000],
       [ 680, 1360, 2040, 2720, 3400, 4080, 4080, 4760, 5440],
       [ 860, 1720, 2580, 3440, 4300, 5160, 5160, 6020, 6880],
       [ 140,  280,  420,  560,  700,  840,  840,  980, 1120]])

In [4]:
arr1 * arr2

array([[  50,  160,  420],
       [ 920, 1750, 3000],
       [4080, 6020, 1120]])

# Q6.

np.pmt(rate, nper, pv) function we will be using in order to calculate monthly mortgage payment before you purchase a house

rate = The periodic interest rate

nper = The number of payment periods

pv = The total value of the mortgage loan

# Q7.

Yes an array can store the string.

The limitation which imposed on the string data is, whenever we store the data of string dtype then it should should keep in mind that the string which is having the maximum length is the limit.

The dtype value is the maximum length of a string in such data. Meaning suppose if any new string we wanted to add, then we can add only that string which have the length either equal to that dtype value or less than tha. If any string which are adding and if its length is more than the dtype value then it will only accpet to maximum length and rest of the characters will not be included.